//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     
//     Les modifications apportées à ce fichier peuvent entraîner un comportement incorrect 
//     et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVCNDB.WPF.Properties;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
{
    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

    public static Settings Default => defaultInstance;

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Light")]
    public string Theme
    {
        get => ((string)(this["Theme"]));
        set => this["Theme"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("#1976D2")]
    public string PrimaryColor
    {
        get => ((string)(this["PrimaryColor"]));
        set => this["PrimaryColor"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
    public string DatabaseServer
    {
        get => ((string)(this["DatabaseServer"]));
        set => this["DatabaseServer"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("50000")]
    public string DatabasePort
    {
        get => ((string)(this["DatabasePort"]));
        set => this["DatabasePort"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("MEDICDB")]
    public string DatabaseName
    {
        get => ((string)(this["DatabaseName"]));
        set => this["DatabaseName"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("root")]
    public string DatabaseUser
    {
        get => ((string)(this["DatabaseUser"]));
        set => this["DatabaseUser"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("10")]
    public int StockAlertThreshold
    {
        get => ((int)(this["StockAlertThreshold"]));
        set => this["StockAlertThreshold"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("30")]
    public int ExpiryAlertDays
    {
        get => ((int)(this["ExpiryAlertDays"]));
        set => this["ExpiryAlertDays"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("1400")]
    public double LastWindowWidth
    {
        get => ((double)(this["LastWindowWidth"]));
        set => this["LastWindowWidth"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("800")]
    public double LastWindowHeight
    {
        get => ((double)(this["LastWindowHeight"]));
        set => this["LastWindowHeight"] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    public bool IsMenuExpanded
    {
        get => ((bool)(this["IsMenuExpanded"]));
        set => this["IsMenuExpanded"] = value;
    }
}
