using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using AVCNDB.WPF.Contracts.Services;
using AVCNDB.WPF.Models;
using AVCNDB.WPF.Services;

namespace AVCNDB.WPF.ViewModels;

public partial class PosoListViewModel : ViewModelBase
{
    private readonly IRepository<Poso> _repository;
    private readonly IRepository<Formes> _formesRepository;
    private readonly IDialogService _dialogService;
    private readonly IExcelService _excelService;
    private readonly IStrictExcelSyncService<Poso> _strictExcelSyncService;
    private readonly MedicSyncService _syncService;

    [ObservableProperty]
    private ObservableCollection<Poso> _posos = new();

    [ObservableProperty]
    private Poso? _selectedPoso;

    [ObservableProperty]
    private string _searchText = string.Empty;

    [ObservableProperty]
    private bool _isEditing;

    // Stored as strings (not decimal) so the user can freely type partial
    // numbers like "1." without the WPF PropertyChanged binding parsing each
    // keystroke and re-rendering "1." back to "1" (the dot would disappear).
    [ObservableProperty]
    private string _editQty = string.Empty;

    [ObservableProperty]
    private string _editPosoForm = string.Empty;

    [ObservableProperty]
    private string _editPrises = string.Empty;

    [ObservableProperty]
    private string _editPeriode = string.Empty;

    public string AutoGeneratedName =>
        $"{EditQty} {EditPosoForm} x {EditPrises} / {EditPeriode}".Trim();

    partial void OnEditQtyChanged(string value) => OnPropertyChanged(nameof(AutoGeneratedName));
    partial void OnEditPosoFormChanged(string value) => OnPropertyChanged(nameof(AutoGeneratedName));
    partial void OnEditPrisesChanged(string value) => OnPropertyChanged(nameof(AutoGeneratedName));
    partial void OnEditPeriodeChanged(string value) => OnPropertyChanged(nameof(AutoGeneratedName));

    [ObservableProperty]
    private string _editConditions = string.Empty;

    [ObservableProperty]
    private string _editNameFormul = string.Empty;

    [ObservableProperty]
    private string _editSubValue = string.Empty;

    [ObservableProperty]
    private ObservableCollection<string> _formeOptions = new();

    public PosoListViewModel(
        IRepository<Poso> repository,
        IRepository<Formes> formesRepository,
        IDialogService dialogService,
        IExcelService excelService,
        IStrictExcelSyncService<Poso> strictExcelSyncService,
        MedicSyncService syncService)
    {
        _repository = repository;
        _formesRepository = formesRepository;
        _dialogService = dialogService;
        _excelService = excelService;
        _strictExcelSyncService = strictExcelSyncService;
        _syncService = syncService;
        _ = LoadDataAsync();
    }

    partial void OnSearchTextChanged(string value) => DebounceSearch(LoadDataAsync);

    private async Task LoadDataAsync()
    {
        await ExecuteAsync(async () =>
        {
            var items = string.IsNullOrWhiteSpace(SearchText)
                ? await _repository.GetAllAsync()
                : await _repository.FindAsync(p =>
                    p.itemname.Contains(SearchText) ||
                    p.posoform.Contains(SearchText) ||
                    p.nameformul.Contains(SearchText) ||
                    p.subvalue.Contains(SearchText));

            Posos = new ObservableCollection<Poso>(items.OrderBy(p => p.itemname));

            // Load forme options for autocomplete (forme posologique field)
            var formes = await _formesRepository.GetAllAsync();
            FormeOptions = new ObservableCollection<string>(
                formes.Select(f => f.itemname)
                      .Where(n => !string.IsNullOrWhiteSpace(n))
                      .OrderBy(n => n));
        }, "Chargement des posologies...");
    }

    [RelayCommand]
    private async Task RefreshAsync() => await LoadDataAsync();

    [RelayCommand]
    private async Task SearchAsync() => await LoadDataAsync();

    [RelayCommand]
    private void AddNew()
    {
        SelectedPoso = null;
        EditQty = string.Empty;
        EditPosoForm = string.Empty;
        EditPrises = string.Empty;
        EditPeriode = string.Empty;
        EditConditions = string.Empty;
        EditNameFormul = string.Empty;
        EditSubValue = string.Empty;
        IsEditing = true;
    }

    [RelayCommand]
    private void Edit(Poso? poso)
    {
        if (poso == null) return;

        SelectedPoso = poso;
        EditQty = poso.qty == 0 ? string.Empty : poso.qty.ToString(System.Globalization.CultureInfo.InvariantCulture);
        EditPosoForm = poso.posoform;
        EditPrises = poso.prises == 0 ? string.Empty : poso.prises.ToString(System.Globalization.CultureInfo.InvariantCulture);
        EditPeriode = poso.periode;
        EditConditions = poso.conditions;
        EditNameFormul = poso.nameformul;
        EditSubValue = poso.subvalue;
        IsEditing = true;
    }

    [RelayCommand]
    private async Task CancelEdit()
    {
        var confirmed = await _dialogService.ShowConfirmAsync(
            "Annuler les modifications",
            "Annuler les modifications en cours ?\nLes données saisies ne seront pas enregistrées.");
        if (confirmed) IsEditing = false;
    }

    [RelayCommand]
    private async Task SaveAsync()
    {
        // Parse decimal inputs (accept both "." and "," as decimal separators)
        var qty = ParseDecimalLoose(EditQty);
        var prises = ParseDecimalLoose(EditPrises);

        if (string.IsNullOrWhiteSpace(EditPosoForm) && qty == 0 && prises == 0)
        {
            await _dialogService.ShowWarningAsync("Validation", "Remplissez au moins la forme posologique.");
            return;
        }

        // Confirmation popup — security check on every save
        var generatedNameLocal = AutoGeneratedName;
        var confirmTitle = SelectedPoso != null ? "Confirmer la modification" : "Confirmer la création";
        var confirmMsg = SelectedPoso != null
            ? $"Enregistrer les modifications apportées à la posologie\n« {generatedNameLocal} » ?"
            : $"Créer la nouvelle posologie\n« {generatedNameLocal} » ?";
        if (!await _dialogService.ShowConfirmAsync(confirmTitle, confirmMsg)) return;

        await ExecuteAsync(async () =>
        {
            var generatedName = AutoGeneratedName;

            if (SelectedPoso != null)
            {
                SelectedPoso.itemname = generatedName;
                SelectedPoso.qty = qty;
                SelectedPoso.posoform = EditPosoForm;
                SelectedPoso.prises = prises;
                SelectedPoso.periode = EditPeriode;
                SelectedPoso.conditions = EditConditions;
                SelectedPoso.nameformul = EditNameFormul;
                SelectedPoso.subvalue = EditSubValue;
                await _repository.UpdateAsync(SelectedPoso);
            }
            else
            {
                await _repository.AddAsync(new Poso
                {
                    itemname = generatedName,
                    qty = qty,
                    posoform = EditPosoForm,
                    prises = prises,
                    periode = EditPeriode,
                    conditions = EditConditions,
                    nameformul = EditNameFormul,
                    subvalue = EditSubValue
                });
            }

            IsEditing = false;
            await LoadDataAsync();
            await _dialogService.ShowSuccessAsync("Sauvegarde réussie", "Posologie enregistrée avec succès.");
        }, "Sauvegarde...");
    }

    /// <summary>
    /// Parse a user-typed number accepting both "." and "," as decimal separators
    /// (French users often type either). Returns 0 for empty/invalid input.
    /// </summary>
    private static decimal ParseDecimalLoose(string? text)
    {
        if (string.IsNullOrWhiteSpace(text)) return 0m;
        var normalized = text.Trim().Replace(',', '.');
        return decimal.TryParse(normalized, System.Globalization.NumberStyles.Any,
                                System.Globalization.CultureInfo.InvariantCulture, out var v)
            ? v : 0m;
    }

    [RelayCommand]
    private async Task DeleteAsync(Poso? poso)
    {
        if (poso == null) return;

        var confirm = await _dialogService.ShowConfirmAsync(
            "Confirmer la suppression",
            $"Supprimer '{poso.itemname}' ?");

        if (!confirm) return;

        await ExecuteAsync(async () =>
        {
            await _repository.DeleteAsync(poso);
            await LoadDataAsync();
        }, "Suppression...");
    }

    [RelayCommand]
    private async Task ExportAsync()
    {
        var filePath = _dialogService.ShowSaveFileDialog(
            "Excel Files|*.xlsx",
            $"Poso_{DateTime.Now:yyyyMMdd}",
            "Exporter les posologies");

        if (string.IsNullOrEmpty(filePath)) return;

        await ExecuteAsync(async () =>
        {
            var checkedItems = Posos.Where(p => p.IsChecked).ToList();
            IEnumerable<Poso> dataToExport;
            string exportInfo;

            if (checkedItems.Count > 0)
            {
                dataToExport = checkedItems;
                exportInfo = $"{checkedItems.Count} element(s) selectionne(s) exporte(s)";
            }
            else
            {
                dataToExport = await _repository.GetAllAsync();
                exportInfo = $"{dataToExport.Count()} element(s) exporte(s)";
            }

            await _excelService.ExportAsync(dataToExport, filePath, "Poso");
            await _dialogService.ShowSuccessAsync("Export reussi", $"{exportInfo}\n{filePath}");
        }, "Export en cours...");
    }

    [RelayCommand]
    private async Task DownloadExcelTemplateAsync()
    {
        var filePath = _dialogService.ShowSaveFileDialog(
            "Excel Files|*.xlsx",
            $"Poso_Template_{DateTime.Now:yyyyMMdd}",
            "Telecharger le modele Excel");

        if (string.IsNullOrEmpty(filePath)) return;

        await ExecuteAsync(async () =>
        {
            await _strictExcelSyncService.CreateTemplateAsync(filePath, "Poso");
            await _dialogService.ShowSuccessAsync(
                "Modele genere",
                $"Modele Excel cree : {filePath}\nNe modifiez pas les en-tetes de colonnes.");
        }, "Generation du modele...");
    }

    [RelayCommand]
    private async Task ImportFromExcelAsync()
    {
        var filePath = _dialogService.ShowOpenFileDialog(
            "Excel Files|*.xlsx;*.xls",
            "Importer les posologies depuis Excel");

        if (string.IsNullOrEmpty(filePath)) return;

        await ExecuteAsync(async () =>
        {
            var result = await _strictExcelSyncService.ImportAndSyncAsync(filePath, "Poso");

            if (!result.IsValid)
            {
                await _dialogService.ShowErrorAsync("Erreur de validation", string.Join("\n", result.Errors));
                return;
            }

            await LoadDataAsync();
            await _dialogService.ShowSuccessAsync(
                "Import Excel termine",
                $"Lignes lues : {result.RowCount}\nInseres : {result.InsertedCount}\nMis a jour : {result.UpdatedCount}\nIgnores : {result.SkippedCount}");
        }, "Import en cours...");
    }

    [RelayCommand]
    private async Task ApplySubstitutsAsync()
    {
        var confirm = await _dialogService.ShowConfirmAsync(
            "Appliquer les substituts",
            "Cette action remplacera chaque dénomination Posologie par son substitut. Continuer ?");

        if (!confirm) return;

        await ExecuteAsync(async () =>
        {
            var result = await _syncService.ApplyPosoSubstitutsAsync();
            await LoadDataAsync();

            if (!string.IsNullOrWhiteSpace(result.ErrorMessage))
            {
                await _dialogService.ShowErrorAsync(
                    "Application des substituts échouée",
                    $"Erreur: {result.ErrorMessage}");
                return;
            }

            await _dialogService.ShowSuccessAsync(
                "Substituts appliqués",
                $"Candidats: {result.CandidateCount}\n" +
                $"Remplacements appliqués: {result.AppliedCount}\n" +
                $"Posologies mises à jour: {result.UpdatedEntityCount}");
        }, "Application des substituts...");
    }
}
